[theme]
primaryColor = "#A8DADC"  # Light Sky Blue - soft, calming blue
backgroundColor = "#F1FAEE"  # Off-white with a hint of warmth for a clean look
secondaryBackgroundColor = "#E0FBFC"  # Light cyan - adds a refreshing touch
textColor = "#1D3557"  # Dark Blue - excellent readability without being too harsh
font = "Segoe UI, Tahoma, sans-serif"  # Modern, clean, and highly readable font

# Border Range Configuration (if needed)
[border]
borderColor = "#457B9D"  # Light Steel Blue - subtle, professional border
borderWidth = "2px"  # Thin border for a sleek, light look
borderRadius = "6px"  # Slightly rounded corners for a soft touch
