[theme]
primaryColor = "#B0E0E6"  # Sky Blue
backgroundColor =  "#87CEEB" # Powder Blue
secondaryBackgroundColor = "#4682B4"  # Steel Blue
textColor = "#FFFFFF"  # White text for better contrast
font = "Arial, Helvetica, sans-serif"  # Font remains Arial

# Border Range Configuration (if needed)
[border]
borderColor = "#00BFFF"  # Deep Sky Blue for border
borderWidth = "3px"  # 3px border width
borderRadius = "10px"  # Slightly larger rounded corners
