[theme]
primaryColor = "#4682B4"  # Steel Blue - cool and professional
backgroundColor = "#F0F8FF"  # Alice Blue - soft and light background
secondaryBackgroundColor = "#6A5ACD"  # Slate Blue - a subtle yet vibrant accent
textColor = "#2F4F4F"  # Dark Slate Gray - good readability without being harsh
font = "Verdana, Geneva, sans-serif"  # Clean and readable font

# Border Range Configuration (if needed)
[border]
borderColor = "#808080"  # Gray - neutral, balanced border color
borderWidth = "2px"  # 2px border width for clean and refined edges
borderRadius = "8px"  # Rounded corners with moderate radius for smooth look
