[theme]
primaryColor = "#5F9EA0"  # Cadet Blue - a muted and sophisticated blue
backgroundColor = "#F0F8FF"  # Alice Blue - a soft, light background
secondaryBackgroundColor = "#4682B4"  # Steel Blue - a balanced blue shade
textColor = "#333333"  # Dark Gray for better readability and contrast
font = "Arial, Helvetica, sans-serif"  # Font remains Arial

# Border Range Configuration (if needed)
[border]
borderColor = "#A9A9A9"  # Dark Gray for subtle borders
borderWidth = "2px"  # Slightly thinner border for a cleaner look
borderRadius = "8px"  # Rounded corners with a moderate radius
