[theme]
primaryColor = "#E694FF"
backgroundColor = "#00172B"
secondaryBackgroundColor = "#0083B8"
textColor = "#DCDCDC"
font = "sans-serif"

# Border Range Configuration (if needed)
[border]
borderColor = "#457B9D"  # Light Steel Blue - subtle, professional border
borderWidth = "2px"  # Thin border for a sleek, light look
borderRadius = "6px"  # Slightly rounded corners for a soft touch
