[theme]
primaryColor = "#4C9F70"  # Medium Sea Green - calming and natural
backgroundColor = "#FAF9F6"  # Very light beige - neutral and warm
secondaryBackgroundColor = "#A9A9A9"  # Dark Gray - subtle accent to contrast with light background
textColor = "#333333"  # Dark Charcoal - for good text readability
font = "Helvetica, Arial, sans-serif"  # Clean and professional font

# Border Range Configuration (if needed)
[border]
borderColor = "#DCDCDC"  # Gainsboro - light gray border for a soft look
borderWidth = "2px"  # Thin border for elegance
borderRadius = "6px"  # Smooth corners with a moderate radius
